# This is example 8.2 of Fish's *A First Course in Finite Elements*

## in which a heat conduction problem with a single quadrilateral element is solved

In [1]:
from IPython.display import Math,display
import sympy,numpy,scipy.integrate

In [2]:
xy=sympy.Matrix([[0,0,2,2],[1,0,sympy.Rational(1,2),1]]).T
display(xy)

Matrix([
[0,   1],
[0,   0],
[2, 1/2],
[2,   1]])

In [3]:
# corrdinate of parent domain
xi,eta=sympy.symbols('xi eta')
# shape functions
N=sympy.Rational(1,4)*sympy.Matrix([(1-xi)*(1-eta),(1+xi)*(1-eta),(1+xi)*(1+eta),(1-xi)*(1+eta)]).T
display(N)
# partial(N1,N2,N3,N4)/partial(xi,eta)
GN=sympy.Matrix([[sympy.diff(i,xi) for i in N],[sympy.diff(i,eta) for i in N]])
display(GN)

Matrix([[(1 - eta)*(1 - xi)/4, (1 - eta)*(xi + 1)/4, (eta + 1)*(xi + 1)/4, (1 - xi)*(eta + 1)/4]])

Matrix([
[eta/4 - 1/4, 1/4 - eta/4, eta/4 + 1/4, -eta/4 - 1/4],
[ xi/4 - 1/4, -xi/4 - 1/4,  xi/4 + 1/4,   1/4 - xi/4]])

In [4]:
# J is partial(x,y)/partial(xi,eta)
J=GN*xy
Jdet=sympy.simplify(J.det())
Jinv=sympy.simplify(J**(-1))
display(J,Jdet,Jinv)

Matrix([
[0, eta/8 - 3/8],
[1,  xi/8 + 1/8]])

3/8 - eta/8

Matrix([
[-(xi + 1)/(eta - 3), 1],
[        8/(eta - 3), 0]])

In [5]:
# partial(N1,N2,N3,N4)/partial(x,y)
NablaN=sympy.simplify(Jinv*GN)
display(NablaN)

Matrix([
[(-eta - xi + 2)/(2*(eta - 3)), (xi + 1)/(2*(eta - 3)),   -(xi + 1)/(eta - 3), (eta + 2*xi - 1)/(2*(eta - 3))],
[        2*(eta - 1)/(eta - 3),  2*(1 - eta)/(eta - 3), 2*(eta + 1)/(eta - 3),         -(2*eta + 2)/(eta - 3)]])

In [6]:
K=numpy.zeros((4,4))
for i in range(4):
    for j in range(i+1):
        f=sympy.lambdify([xi,eta],Jdet*(NablaN[:,i].T*NablaN[:,j])[0])
        K[i,j]=scipy.integrate.dblquad(f,-1,1,-1,1)[0]
        if j<i:
            K[j,i]=K[i,j]
# The K matrix on page 199
print(5*K)

[[ 4.77675494 -3.52675494 -2.94649013  1.69649013]
 [-3.52675494  4.15175494  1.69649013 -2.32149013]
 [-2.94649013  1.69649013  6.60701975 -5.35701975]
 [ 1.69649013 -2.32149013 -5.35701975  5.98201975]]
